import pygame

START_EVENT = pygame.USEREVENT + 1
PAUSE_EVENT = pygame.USEREVENT + 2
STOP_EVENT = pygame.USEREVENT + 3
BACK_EVENT = pygame.USEREVENT + 4
SELECT_ALGO_EVENT = pygame.USEREVENT + 5
SELECT_MAP_EVENT = pygame.USEREVENT + 6
RUN_EVENT = pygame.USEREVENT + 7
